apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dvw263kte-go
  janus-idp.io/tekton: dvw263kte-go
  backstage.io/kubernetes-id: dvw263kte-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dvw263kte-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
