apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dvw263kte-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dvw263kte-go 
  name: dvw263kte-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dvw263kte-go
    weight: 100 
